### ISSUE TITLE
Add support for arguments on "link-project" to support multiple foundry instances

### ISSUE THREAD

**Issue by ccjmk** [ghost-fvtt/foundry-factory#318]
(EDIT: fat-fingered an enter, filling in the description now)

It could be useful being able to have more than a single dataPath on the `foundryconfig.json` and using one or another based on an argument (defaulting to dataPath if no argument sent?). Use case is for example, having two local foundry installations, a node and an electron, used as test benches for two different foundry version (right now I have a v10 node i'm using to develop for v10 and I keep the electron app on v9 for supporting my existing modules)

I imagine the simplest approach would be having a `foundryconfig.json` like:

```json
{
    "dataPath": "path/to/data",
    "node": "path/to/one/foundrys/data",
    "win": "path/to/another/foundrys/data",
}
``` 

with 'npm run link-project' using `dataPath`, 'node run link-project node' using the node path, etc.

**Comment by ghost91-** [comment]
It's a good idea, I still have to think a little about the format, though. I'd prefer for the different paths not to be just properties in the main object, because that would make it impossible to introduce other properties later on, without a breaking changed. I could imagine something like allowing `dataPath` to be an object, that has a mapping of identifiers and paths, i.e. something like
```json
{
  "dataPath": {
    "default": "path/to/data",
    "node": "path/to/one/foundrys/data",
    "win": "path/to/another/foundrys/data"
  }
}
```
another alternative would be to just have an array of config objects at the top level, and assign each object an identifier:
```json
[
  { "id": "default", "dataPath": "path/to/data" },
  { "id": "node", "dataPath": "path/to/one/foundrys/data" },
  { "id": "win", "dataPath": "path/to/another/foundrys/data" }
]
```
And I can think of even more alternatives. Basically the idea is future proofing the format a little.

**Comment by ccjmk** [comment]
I like the second the most, I wonder if it would make sense to preemptively refactor that into a sort of `profiles` key in case you want to add more configurable shenanigans on the json, like

```
{
    "whateverSetting": "thisAffectsSomethingRegardlessOfProfile"
    "profiles": [
        { "id": "default", "dataPath": "path/to/data" },
        { "id": "node", "dataPath": "path/to/one/foundrys/data" },
        { "id": "win", "dataPath": "path/to/another/foundrys/data" }
    ]
}
```

**Comment by ghost91-** [comment]
yeah, that's basically the third option I was thinking about. That might make the most sense...
